
import { MenuPage, CommandConfig, QueueItem, SavedChannel } from '../types';

export const generateWorkerCode = (
    token: string, 
    menus: Record<string, MenuPage>, 
    commands: CommandConfig[],
    queue: QueueItem[],
    channels: SavedChannel[]
): string => {

    // Filter queue to only include pending items
    const pendingQueue = queue.filter(q => q.status === 'pending');

    return `
/**
 * 🤖 Generated by AdminGlass Panel
 * 📅 Generated At: ${new Date().toISOString()}
 * 
 * INSTRUCTIONS:
 * 1. Copy this code.
 * 2. Create a new Worker in Cloudflare.
 * 3. Paste this code.
 * 4. Add a Cron Trigger (e.g., "* * * * *") if you have scheduled messages.
 * 5. Deploy!
 */

const TOKEN = "${token}";
const MENUS = ${JSON.stringify(menus, null, 2)};
const COMMANDS = ${JSON.stringify(commands, null, 2)};
const QUEUE = ${JSON.stringify(pendingQueue, null, 2)};
const CHANNELS = ${JSON.stringify(channels, null, 2)};

// --- MAIN ENTRY POINT ---
export default {
  async fetch(request, env, ctx) {
    if (request.method === "POST") {
      try {
        const update = await request.json();
        await handleUpdate(update);
      } catch (e) {
        console.error(e);
      }
      return new Response("OK");
    }
    return new Response("Bot is running in Cloud Mode ☁️");
  },

  // --- CRON JOB HANDLER (FOR SCHEDULED MESSAGES) ---
  async scheduled(event, env, ctx) {
    const now = Date.now();
    // Logic: Send message if scheduled time is passed within the last 15 minutes (to avoid re-sending old ones forever in a static worker)
    // Note: Since this is a static export, we can't "delete" from QUEUE array permanently. 
    // We rely on the time window.
    
    for (const item of QUEUE) {
       const timeDiff = now - item.createdAt;
       // If the time has passed (positive diff) AND it's less than 15 minutes ago
       if (timeDiff >= 0 && timeDiff < 15 * 60 * 1000) {
           await processQueueItem(item);
       }
    }
  }
};

// --- LOGIC HANDLERS ---

async function handleUpdate(update) {
  // 1. Handle Callbacks (Button Clicks)
  if (update.callback_query) {
    const data = update.callback_query.data;
    const chatId = update.callback_query.message.chat.id;
    const callbackId = update.callback_query.id;

    // Check if it's a menu navigation
    if (MENUS[data]) {
      await sendMenu(chatId, MENUS[data]);
      await answerCallback(callbackId);
      return;
    }

    // Check if it's "root" or "back"
    if (data === 'root' && MENUS['root']) {
      await sendMenu(chatId, MENUS['root']);
      await answerCallback(callbackId);
      return;
    }
    
    await answerCallback(callbackId);
    await sendMessage(chatId, "⚠️ دستور ناشناخته یا فرم (فرم‌ها در حالت ابری پشتیبانی نمی‌شوند).");
  }

  // 2. Handle Messages (Commands & Text)
  if (update.message && update.message.text) {
    const text = update.message.text;
    const chatId = update.message.chat.id;
    const user = update.message.from;

    // Commands
    if (text.startsWith('/')) {
        const cmdName = text.substring(1).split(' ')[0].toLowerCase();
        
        // Check custom commands
        const matched = COMMANDS.find(c => c.command === cmdName);
        if (matched) {
            if (matched.actionType === 'text') {
                 await sendMessage(chatId, processVariables(matched.actionValue, user));
            } else if (matched.actionType === 'menu' && MENUS[matched.actionValue]) {
                 await sendMenu(chatId, MENUS[matched.actionValue], user);
            }
            return;
        }

        if (cmdName === 'start' && MENUS['root']) {
            await sendMenu(chatId, MENUS['root'], user);
            return;
        }
    }
  }
}

async function processQueueItem(item) {
   // Determine targets
   let targets = [];
   if (item.targetChannelId === 'all' || item.targetChannelId === 'BROADCAST_ALL') {
       // In static mode, we can't access dynamic user list easily unless exported.
       // We skip 'all' broadcast in simple static export to verify safety.
       // Only specific channels:
       return; 
   } else {
       targets = [item.targetChannelId];
   }

   const kb = item.rows && item.rows.length > 0 ? {
       inline_keyboard: item.rows.map(r => r.buttons.map(b => ({
           text: b.text,
           url: b.type === 'link' ? b.value : undefined,
           callback_data: b.type !== 'link' ? (b.value || 'noop') : undefined
       })))
   } : undefined;

   for (const targetId of targets) {
       if (item.hasMedia && item.mediaFiles.length > 0) {
           // Priority: FileID -> URL
           const m = item.mediaFiles[0];
           const fileRef = m.fileId || m.url;
           if(m.type === 'image') await sendPhoto(targetId, fileRef, item.content, kb);
           else if(m.type === 'video') await sendVideo(targetId, fileRef, item.content, kb);
           else await sendDocument(targetId, fileRef, item.content, kb);
       } else {
           await sendMessage(targetId, item.content, kb);
       }
   }
}

// --- TELEGRAM API HELPERS ---

async function api(method, body) {
  const url = \`https://api.telegram.org/bot\${TOKEN}/\${method}\`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });
  return await res.json();
}

async function sendMessage(chatId, text, replyMarkup) {
  return await api('sendMessage', {
    chat_id: chatId,
    text: text,
    reply_markup: replyMarkup,
    parse_mode: 'HTML'
  });
}

async function sendPhoto(chatId, photo, caption, replyMarkup) {
  return await api('sendPhoto', { chat_id: chatId, photo, caption, reply_markup: replyMarkup, parse_mode: 'HTML' });
}

async function sendVideo(chatId, video, caption, replyMarkup) {
  return await api('sendVideo', { chat_id: chatId, video, caption, reply_markup: replyMarkup, parse_mode: 'HTML' });
}

async function sendDocument(chatId, document, caption, replyMarkup) {
  return await api('sendDocument', { chat_id: chatId, document, caption, reply_markup: replyMarkup, parse_mode: 'HTML' });
}

async function answerCallback(callbackId, text) {
  return await api('answerCallbackQuery', { callback_query_id: callbackId, text });
}

async function sendMenu(chatId, menu, user) {
  const kb = {
    inline_keyboard: [
        ...menu.rows.map(r => r.buttons.map(b => ({
            text: b.text,
            callback_data: b.type === 'link' ? undefined : (b.type==='submenu' ? (b.targetMenuId||'root') : (b.type==='form'?'noop':'noop')), // Forms disabled in static
            url: b.type === 'link' ? b.value : undefined
        }))),
        ...(menu.id !== 'root' ? [[{text: '🏠 منوی اصلی', callback_data: 'root'}, {text: '🔙 بازگشت', callback_data: menu.parentId || 'root'}]] : [])
    ]
  };
  
  let content = processVariables(menu.content, user);

  if (menu.media && menu.media.length > 0) {
       const m = menu.media[0];
       const file = m.fileId || m.url;
       if (m.type === 'image') await sendPhoto(chatId, file, content, kb);
       else if (m.type === 'video') await sendVideo(chatId, file, content, kb);
       else await sendMessage(chatId, content, kb);
  } else {
       await sendMessage(chatId, content, kb);
  }
}

function processVariables(text, user) {
    if (!text) return "";
    if (!user) return text;
    return text
        .replace(/{first_name}|{نام}/g, user.first_name || 'کاربر')
        .replace(/{username}|{یوزرنیم}/g, user.username ? '@' + user.username : 'ندارد')
        .replace(/{id}/g, user.id);
}
    `;
};
